# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85f2f573b58f064e05fa2ffbd9c37a1131600ce75dab2d9b4de7a3486b6815cf2213a78db3d315d7196da8ae5c98df1cc9a35e16a270142d2516beb04dec2a46

test:
  secret_key_base: 5a9c209813060fe33682082e1c7e8c464415307eea0430c1d77664164ba3181e99d17240f1ac9c85b8ecbde70c7e2f5941cc1e9a04eed83c7a88a04806d51538

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
