# A sample Gemfile
source "https://rubygems.org"

gem 'sinatra'
gem 'sinatra-contrib'

# TODO add Redis
# TODO add pry to the development group

gem 'redis'
gem 'pry-rails', :group => :development
bundle install
